name: lint

on:
  push:
    branches:
      - 'disabled'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Run linter"
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.5'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: '--config=./ci/.golangci-lint.yml'